# Generated by Django 5.2.6 on 2025-09-09 15:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField()),
                ('category', models.CharField(choices=[('basket', 'Basket'), ('futsal', 'Futsal'), ('sepatu', 'Sepatu'), ('tas', 'Tas'), ('jersey', 'Jersey')], max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
