# Generated by Django 5.2.6 on 2025-09-16 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_delete_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='News',
        ),
    ]
