# Generated by Django 5.2.6 on 2025-09-16 16:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_product_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('basketball', 'BasketBall'), ('soccerBall', 'SoccerBall'), ('shoes', 'Shoes'), ('backpack', 'Backpack'), ('jersey', 'Jersey')], max_length=20),
        ),
    ]
