# Generated by Django 5.2.6 on 2025-09-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_news_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
